export const initialValues = {
  firstName: '',
  lastName: '',
  email: '',
  password: '',
  confirmPassword: '',
  phone: '',

  dateOfBirth: '',
  sinNumber: '',
  address: '',
  city: '',
  province: '',
  postalCode: '',
  country: 'Canada',

  familyStatus: '',
  maritalStatus: '',
  numberOfDependents: '',

  spouseName: '',
  spouseSin: '',
  spouseDob: '',
  spousePhone: '',

  taxProfile: {
    employment: true,
    gigWork: false,
    selfEmployed: false,
    businessOwner: false,
    unemployed: false,
  },

  spouseTaxProfile: {
    employment: false,
    gigWork: false,
    selfEmployed: false,
    businessOwner: false,
    unemployed: false,
  },

  employmentStatus: '',
  spouseEmploymentStatus: '',

  employerName: '',
  employerBusinessNumber: '',
  employeeId: '',
  t4Income: '',
  cppContributions: '',
  eiContributions: '',

  contractType: '',
  quarterlyFiling: false,

  gigPlatforms: [],
  gigPlatformOther: '',
  gigIncome: '',
  gigExpenses: '',
  gigGstHstCollected: '',
  averageWeeklyKm: '',

  selfEmploymentBusinessName: '',
  selfEmploymentIncome: '',
  selfEmploymentExpenses: '',
  selfEmploymentGstHstCollected: '',

  businessName: '',
  businessType: '',
  businessNumber: '',
  businessIncome: '',
  businessExpenses: '',
  yearEstablished: '',
  numberOfEmployees: '',

  additionalIncomeSources: [],
  investmentIncome: '',
  investmentNotes: '',
  rentalIncome: '',
  rentalPropertyAddress: '',
  foreignIncome: '',
  foreignIncomeCountry: '',
  cryptoIncome: '',
  cryptoNotes: '',

  spouseIncome: '',
  spouseJobTitle: '',
  spouseEmployerName: '',
  spouseFinancialSituation: '',
  shareWithSpouse: false,

  spouseT4Income: '',
  spouseCppContributions: '',
  spouseEiContributions: '',

  spouseGigPlatforms: [],
  spouseGigPlatformOther: '',
  spouseGigIncome: '',
  spouseGigExpenses: '',
  spouseGigGstHstCollected: '',
  spouseAverageWeeklyKm: '',
  spouseContractType: '',
  spouseQuarterlyFiling: false,

  spouseSelfEmploymentBusinessName: '',
  spouseSelfEmploymentIncome: '',
  spouseSelfEmploymentExpenses: '',
  spouseSelfEmploymentGstHstCollected: '',

  spouseBusinessName: '',
  spouseBusinessType: '',
  spouseBusinessNumber: '',
  spouseBusinessIncome: '',
  spouseBusinessExpenses: '',
  spouseYearEstablished: '',
  spouseNumberOfEmployees: '',

  spouseAdditionalIncomeSources: [],
  spouseInvestmentIncome: '',
  spouseInvestmentNotes: '',
  spouseRentalIncome: '',
  spouseRentalPropertyAddress: '',
  spouseForeignIncome: '',
  spouseForeignIncomeCountry: '',
  spouseCryptoIncome: '',
  spouseCryptoNotes: '',

  hasInvestments: false,
  hasRentalIncome: false,
  hasForeignIncome: false,
  hasCrypto: false,
  hasRRSP: false,
  hasFHSA: false,
  hasTFSA: false,
  hasTuition: false,
  hasMedicalExpenses: false,
  hasCharitableDonations: false,
  hasChildCareExpenses: false,
  hasMovingExpenses: false,
  hasUnionDues: false,
  hasToolExpenses: false,
  hasHomeOffice: false,
  hasVehicleExpenses: false,

  receiptTypes: [],
  deductions: {},

  platforms: [],
  spousePlatforms: [],

  vehiclePurchasedForWork: false,
  vehicles: [],

  agreeToTerms: false,
  agreeToPrivacy: false,
  confirmAccuracy: false,
};